[phases.build]
cmds = [
  "npm ci",
  "npm run build:safe"
]

[phases.start]
cmd = "npx prisma db push && npm start"

[variables]
NODE_ENV = "production"
DATABASE_URL = "file:./prod.db"
SKIP_ENV_VALIDATION = "true"